package data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table (name = "extras")
public class Extra {
	/**
	 * The id of this extra (auto generated by db)
	 */
	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column( name = "Id", nullable=false)
	private int id;
	
	/**
	 * The title of this extra.
	 * 1-3 words that describes the extra
	 */
	@Column( name = "Title", nullable=false, length=30)
	private String title;
	
	
	/**
	 * Returns the id of this extra
	 * @return the id of this extra
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets id for this extra
	 * @param id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Returns the title of this extra
	 * @return the title of this extra
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets title to this extra
	 * @param title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

}
